/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IaRouteImport } from './routes/ia'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardConfiguracionRouteImport } from './routes/dashboard.configuracion'
import { Route as DashboardIaRouteImport } from './routes/dashboard.ia'
import { Route as DashboardPerfilRouteImport } from './routes/dashboard.perfil'
import { Route as DashboardReservasRouteImport } from './routes/dashboard.reservas'
import { Route as DashboardServiciosRouteImport } from './routes/dashboard.servicios'
import { Route as DashboardSuscripcionRouteImport } from './routes/dashboard.suscripcion'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfiguracionRoute = DashboardConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIaRoute = DashboardIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReservasRoute = DashboardReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServiciosRoute = DashboardServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSuscripcionRoute = DashboardSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ia': typeof IaRoute
  '/planes': typeof PlanesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/sobre': typeof SobreRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/ia': typeof DashboardIaRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/reservas': typeof DashboardReservasRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/suscripcion': typeof DashboardSuscripcionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ia': typeof IaRoute
  '/planes': typeof PlanesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/sobre': typeof SobreRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/ia': typeof DashboardIaRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/reservas': typeof DashboardReservasRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/suscripcion': typeof DashboardSuscripcionRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/ia': typeof IaRoute
  '/planes': typeof PlanesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/servicios': typeof ServiciosRoute
  '/sobre': typeof SobreRoute
  '/dashboard/configuracion': typeof DashboardConfiguracionRoute
  '/dashboard/ia': typeof DashboardIaRoute
  '/dashboard/perfil': typeof DashboardPerfilRoute
  '/dashboard/reservas': typeof DashboardReservasRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/suscripcion': typeof DashboardSuscripcionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ia'
    | '/planes'
    | '/reset-password'
    | '/servicios'
    | '/sobre'
    | '/dashboard/configuracion'
    | '/dashboard/ia'
    | '/dashboard/perfil'
    | '/dashboard/reservas'
    | '/dashboard/servicios'
    | '/dashboard/suscripcion'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ia'
    | '/planes'
    | '/reset-password'
    | '/servicios'
    | '/sobre'
    | '/dashboard/configuracion'
    | '/dashboard/ia'
    | '/dashboard/perfil'
    | '/dashboard/reservas'
    | '/dashboard/servicios'
    | '/dashboard/suscripcion'
    | '/dashboard'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ia'
    | '/planes'
    | '/reset-password'
    | '/servicios'
    | '/sobre'
    | '/dashboard/configuracion'
    | '/dashboard/ia'
    | '/dashboard/perfil'
    | '/dashboard/reservas'
    | '/dashboard/servicios'
    | '/dashboard/suscripcion'
    | '/dashboard/'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  IaRoute: typeof IaRoute
  PlanesRoute: typeof PlanesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreRoute: typeof SobreRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/configuracion': {
      id: '/dashboard/configuracion'
      path: '/configuracion'
      fullPath: '/dashboard/configuracion'
      preLoaderRoute: typeof DashboardConfiguracionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ia': {
      id: '/dashboard/ia'
      path: '/ia'
      fullPath: '/dashboard/ia'
      preLoaderRoute: typeof DashboardIaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil': {
      id: '/dashboard/perfil'
      path: '/perfil'
      fullPath: '/dashboard/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reservas': {
      id: '/dashboard/reservas'
      path: '/reservas'
      fullPath: '/dashboard/reservas'
      preLoaderRoute: typeof DashboardReservasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servicios': {
      id: '/dashboard/servicios'
      path: '/servicios'
      fullPath: '/dashboard/servicios'
      preLoaderRoute: typeof DashboardServiciosRouteImport
      parentRoute: typeof DashboardRoute
    }
    
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardConfiguracionRoute: typeof DashboardConfiguracionRoute
  DashboardIaRoute: typeof DashboardIaRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardReservasRoute: typeof DashboardReservasRoute
  DashboardServiciosRoute: typeof DashboardServiciosRoute
  DashboardSuscripcionRoute: typeof DashboardSuscripcionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConfiguracionRoute: DashboardConfiguracionRoute,
  DashboardIaRoute: DashboardIaRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardReservasRoute: DashboardReservasRoute,
  DashboardServiciosRoute: DashboardServiciosRoute,
  DashboardSuscripcionRoute: DashboardSuscripcionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  IaRoute: IaRoute,
  PlanesRoute: PlanesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiciosRoute: ServiciosRoute,
  SobreRoute: SobreRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
